version: 2.1

commands:
  requirements:
    steps:
      - run:
          name: Create a virtualenv environment
          command: "virtualenv venv"

      - run:
          name: Install requirements
          command: ". venv/bin/activate && make requirements"

jobs:
  python38-quality:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          keys: python3.8
      - requirements
      - run:
          name: Run code quality checks
          command: . venv/bin/activate && tox -e quality
      - save_cache:
          key: python3.8
          paths:
            - .tox
            - venv
            - /home/circleci/.cache/pip

  python38:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          keys: python3.8
      - requirements
      - run:
          name: Run tests using Python 3.8
          command: . venv/bin/activate && tox -e "py{38}-django{22}"
      - save_cache:
          key: python3.8
          paths:
            - .tox
            - venv
            - /home/circleci/.cache/pip

  pii_check:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          keys: python3.8
      - requirements
      - run:
          name: Run PII checks
          command: . venv/bin/activate && tox -e pii_check
      - save_cache:
          key: python3.8
          paths:
            - .tox
            - venv
            - /home/circleci/.cache/pip

workflows:
  version: 2
  main:
    jobs:
      - python38-quality
      - python38
      - pii_check
